### ISSUE TITLE
New Backend: "Bevin"

### ISSUE THREAD

**Issue by oubiwann** [ut-proj/undertone#80]
@gbevin has a couple of open source CLI tools for sending/receiving MIDI:

* https://github.com/gbevin/SendMIDI
* https://github.com/gbevin/ReceiveMIDI

For situations where these are the only thing needed by a user, Extempore would be overkill (and the `bevin` backend would thus be quite welcome).

Ideally, we'd be able to start up two OS processes, one for each, put them  in the supervision tree, and then pipe (using Erlang ports) commands as needed to these ... will have to look at the tools more to see what's possible. Even without that, though, it might still be worth the cost of an OS process for every command as a tradeoff for the increased simplicity of a backend like this.

Tasks/features:

* [ ] Download & install the tools and explore their capabilities
* [ ] Add configuration for new backend
* [ ] Add map or struct for CLI tools' options
* [ ] Create `gen_server`s for each, with spawned ports for the OS process
* [ ] Select appropriate restart strategy(ies)
* [ ] Add health checks for ports/processes
* [ ] Adapt `xt.midi:cc`, `xt.midi:cc-ramp`, etc. for use with this backend
* [ ] Add examples

**Comment by oubiwann** [comment]
Video for setup on Mac:
* https://www.youtube.com/watch?v=_o1kg0IbetY

First 1/3rd is for beginners. Notes on the rest:
* an Erlang port can read `receivemidi`'s output
* multiple `cc`s can be sent at the same time
* Bidule might be nice to put in the docs to help users more easily set up MIDI
* yes! `sendmidi --` is supported!

**Comment by oubiwann** [comment]
If this goes well, I might demo this at the next conference! (CodeBEAM in March).

**Comment by oubiwann** [comment]
Downloaded:
* https://github.com/gbevin/SendMIDI/releases/tag/1.0.15
* https://github.com/gbevin/ReceiveMIDI/releases/tag/1.1.0

**Comment by oubiwann** [comment]
Added a question at https://github.com/gbevin/SendMIDI/issues/29 for guidance in adding MIDI time clock & code support in the backend.

**Comment by oubiwann** [comment]
Basic reading and writing to the open Erlang ports for the OS process is working quite well (as expected). One problem so far, is that exiting the server doesn't seem to be causing the `receivemidi` process to exit. `sendmidi` exits just find, though.

**Comment by oubiwann** [comment]
> Basic reading and writing to the open Erlang ports for the OS process is working quite well (as expected). One problem so far, is that exiting the server doesn't seem to be causing the `receivemidi` process to exit. `sendmidi` exits just find, though.

This has its own ticket now: #88
